import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import TanStackProvider from "@/providers/TanStackProvider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackProvider>
          <Header />
          <main className="pt-20">
            <div className="max-w-[2520px] mx-auto xl:px-20 md:px-10 sm:px-2 px-4">
              <div className="mx-auto min-h-[80vh] h-full">
                {children}
              </div>
            </div>
          </main>
        </TanStackProvider>
      </body>
    </html>
  );
}
